// Draft copy, deliberately separated from layout. Do not remove the draft
// notices before operator, vendor contracts, consent and product terms are checked.
export const pages = {
  impressum: {
    title: 'Impressum',
    body: `<p class="draft-notice"><strong>Entwurf vor dem Unternehmensstart.</strong><br>Die Gewerbeanmeldung ist nach Angaben des Gründers geplant. Die endgültige Betreiberstellung, Rechtsform und gegebenenfalls weitere Pflichtangaben müssen vor der Veröffentlichung bestätigt werden.</p>
    <h2>Vorgesehener Anbieter</h2>
    <address>Armin Brnicanin<br>Novaire<br>Hopfenstraße 60<br>51109 Köln<br>Deutschland</address>
    <p>Projektleitung: Armin Brnicanin, Gründer &amp; CEO. „CEO“ ist hier eine Funktionsbezeichnung im Projekt und keine Angabe einer Rechtsform oder Registerstellung.</p>
    <h2>Kontakt</h2><p>E-Mail: <a href="mailto:support@novaireai.de">support@novaireai.de</a><br>Website: www.novaireai.de</p>
    <h2>Unternehmensangaben</h2><p>Es werden derzeit keine Handelsregisternummer, Umsatzsteuer-Identifikationsnummer oder Wirtschafts-Identifikationsnummer angegeben, da diese für den Entwurf nicht bestätigt wurden. Erforderliche Angaben sind vor Veröffentlichung zu ergänzen. Es wird keine GmbH, UG oder andere eingetragene Gesellschaft behauptet.</p>
    <h2>Marken und Inhalte</h2><p>Novaire ist eine eigenständige Lern-App. Die Namen und Logos von OpenAI und Anthropic dienen der Benennung der eingebundenen Technologieanbieter. Sie sind keine Aussage über eine Partnerschaft, Empfehlung oder Unterstützung durch diese Unternehmen. Rechte an fremden Marken verbleiben bei den jeweiligen Rechteinhabern.</p>
    <p>Die App-Abbildungen zeigen Entwicklungsstände und ein fiktives Beispielprofil. Funktionen und Gestaltung können sich bis zur Veröffentlichung ändern.</p>
    <h2>Vor Veröffentlichung zu klären</h2><p class="pending-detail">Endgültige Betreiberstellung und Rechtsform; gegebenenfalls Register- und Identifikationsangaben; erforderliche Angaben zur Verbraucherstreitbeilegung; Nutzungsrechte und Markenprüfung für Novaire und das Logo. Dieser Entwurf bestätigt keine abgeschlossene rechtliche Prüfung.</p>`
  },
  datenschutz: {
    title: 'Datenschutz',
    body: `<p class="draft-notice"><strong>Arbeitsentwurf · nicht als abschließend geprüfte Datenschutzerklärung verwenden.</strong><br>Website und App sind getrennt beschrieben. Vertragspartner, Verarbeitungsorte, Löschfristen und der Einwilligungsprozess für Kinder sind vor dem Start verbindlich zu prüfen und zu ergänzen. Stand: 30. September 2026.</p>
    <h2>1. Wer ist verantwortlich?</h2><p>Vorgesehener Verantwortlicher ist Armin Brnicanin, Hopfenstraße 60, 51109 Köln, Deutschland. Datenschutzanfragen: <a href="mailto:support@novaireai.de">support@novaireai.de</a>. Die Betreiberstellung wird vor der Veröffentlichung abschließend bestätigt.</p>
    <h2>2. Kurz erklärt</h2><p>Diese Website stellt Novaire vor. Hier gibt es keinen KI-Chat, keine Anmeldung, keine Käufe und keinen Zugriff auf dein Mikrofon oder deinen Standort. Wenn du uns eine E-Mail schreibst, erhalten wir deine E-Mail-Adresse und den Inhalt deiner Nachricht. In der App können zusätzlich Konto-, Lern- und Inhaltsdaten verarbeitet werden.</p><p>Bitte schicke uns keine Passwörter, Zahlungsdaten oder unnötigen Angaben über dich, Mitschüler oder andere Personen. Bei Fragen kannst du dich gemeinsam mit deinen Eltern an uns wenden.</p>
    <h2>3. Besuch dieser Website</h2><p>Für die Bereitstellung ist Vercel als Hosting-Anbieter vorgesehen. Beim Abruf einer Seite fallen technisch unter anderem IP-Adresse, Zeitpunkt, angeforderte Adresse, Browserinformationen und Statusdaten an. Diese sind für Auslieferung, Sicherheit und Fehleranalyse relevant. Als Rechtsgrundlage für den notwendigen technischen Betrieb kommt Art. 6 Abs. 1 lit. f DSGVO in Betracht; das berechtigte Interesse liegt in einer sicheren und zuverlässigen Bereitstellung.</p><p>Die von uns erstellte Website setzt keine Analyse- oder Werbe-Cookies ein und verwendet kein Local Storage. Schriften werden aus dem Betriebssystem geladen; Bilder, Logos, Styles und Skripte werden zusammen mit der Website ausgeliefert. Es gibt keine eingebetteten Social-Media-Inhalte und keine automatisch geladenen Drittanbieter-Videos. Das gilt für diesen Codebestand, nicht für nachträglich aktivierte Hosting-Erweiterungen.</p><p class="pending-detail">Vor dem öffentlichen Betrieb: konkreten Vercel-Vertragspartner, Auftragsverarbeitungsvertrag, aktivierte Hosting-Funktionen, Aufbewahrung technischer Protokolle und Drittlandtransfermechanismen bestätigen. Informationen des Anbieters: <a href="https://vercel.com/legal/dpa">Vercel DPA</a> und <a href="https://vercel.com/legal/privacy-notice">Vercel Privacy Notice</a>.</p>
    <h2>4. E-Mail und Support</h2><p>Wenn du uns kontaktierst, verarbeiten wir deine Absenderadresse, den Inhalt, freiwillige Anhänge und gegebenenfalls Angaben zu deinem Konto, um dein Anliegen zu beantworten. Für den E-Mail-Dienst wird nach Betreiberangabe IONOS eingesetzt. Eine Telefonnummer erhalten wir nur, wenn sie tatsächlich von dir angegeben oder im eingesetzten Verfahren erhoben wird; sie ist nicht automatisch Bestandteil jeder Registrierung.</p><p>Je nach Anfrage ist die Rechtsgrundlage Art. 6 Abs. 1 lit. b DSGVO für vertragliche oder vorvertragliche Anliegen oder Art. 6 Abs. 1 lit. f DSGVO für die Bearbeitung allgemeiner Anfragen. Ein Bezug zu Novaire ist keine pauschale Erlaubnis für beliebige weitere Nutzung. Newsletter und Werbung sind in dieser Website nicht eingebaut.</p><p>Supportdaten sollen gelöscht werden, sobald das Anliegen erledigt ist und keine notwendigen Nachweise, offenen Ansprüche oder gesetzlichen Aufbewahrungspflichten entgegenstehen. <span class="pending-detail">Die dafür umgesetzten Fristen und regelmäßigen Löschläufe sowie der konkrete IONOS-Vertrag müssen vor Veröffentlichung festgelegt werden.</span></p>
    <h2>5. Konto und Lernprofil in der App</h2><p>Die App verwendet Supabase für Konten und Backend-Funktionen. Je nach aktivierter Funktion können eine eindeutige Nutzer-ID (UUID), E-Mail-Adresse, Anzeigename, Altersangabe, Klasse, Bundesland, Lernziele, Einstellungen, Lernfortschritt und Nutzungsinformationen verarbeitet werden. Eine UUID ist eine technische Zuordnung und macht Daten nicht anonym.</p><p>Klasse und Bundesland werden vom Nutzer angegeben; daraus folgt keine automatische Standortfreigabe. Zugriff auf Kontaktdaten darf nur erfolgen, soweit er für konkrete Aufgaben wie Kontoverwaltung, Sicherheit und Support erforderlich ist. Berechtigungen und organisatorische Zugangsbeschränkungen sind vor dem Start zu prüfen.</p><p>Für erforderliche Kontofunktionen bei einem wirksamen Nutzungsvertrag kommt Art. 6 Abs. 1 lit. b DSGVO in Betracht, für gesonderte freiwillige Funktionen gegebenenfalls Art. 6 Abs. 1 lit. a DSGVO. Die passende Rechtsgrundlage ist pro Verarbeitung festzulegen, nicht pauschal durch das Akzeptieren einer Datenschutzerklärung.</p>
    <h2>6. KI-Anfragen, Dateien und Sprache</h2><p>Wenn du in der App eine KI-Funktion verwendest, müssen dafür notwendige Inhalte an die jeweils eingesetzten Anbieter übermittelt werden. Der geprüfte lokale Code bindet OpenAI und Anthropic ein. Dazu können Fragen, ausgewählte Gesprächsinhalte, hochgeladene Bilder oder Dokumente und notwendiger Lernkontext gehören. Bei aktivierter Sprachfunktion können Audio und Transkripte verarbeitet werden. Der bloße Besuch dieser Website löst keine solche KI-Anfrage aus.</p><p>Bitte lade nur Inhalte hoch, die du verwenden darfst. Vermeide sensible persönliche Angaben, etwa Gesundheitsdaten, und personenbezogene Daten anderer Menschen, wenn sie für deine Lernfrage nicht erforderlich sind.</p><p class="pending-detail">Vor dem App-Start sind die tatsächlich eingesetzten Dienste einschließlich Unterauftragnehmern, Datenflüsse, Speicherorte, Löschfristen, Audioverarbeitung, Trainings- und Aufbewahrungseinstellungen sowie Verträge zu bestätigen. Aus der lokalen Konfiguration lässt sich keine Garantie „keine Speicherung“, „kein Training“ oder „ausschließlich EU-Verarbeitung“ ableiten.</p>
    <h2>7. Lernfortschritt und Empfehlungen</h2><p>Die App kann Antworten, bearbeitete Themen und Wiederholungen auswerten, um passende nächste Lernschritte vorzuschlagen. Solche Einschätzungen sind Lernhilfen, keine Schulnoten und keine verbindlichen Urteile über deine Fähigkeiten. Eine Übermittlung an Eltern oder Schulen ist durch diese Website nicht eingerichtet. <span class="pending-detail">Vor Start sind Umfang, Rechtsgrundlage, Speicherfristen, Profilbildung und erforderliche Schutzmaßnahmen für Minderjährige zu dokumentieren.</span></p>
    <h2>8. Käufe und Freischaltungen</h2><p>App-Käufe sind über den Apple App Store vorgesehen. RevenueCat soll Kaufstatus und Berechtigungen verwalten; Supabase ordnet diese dem App-Konto zu. Dafür können Nutzer-ID, Produktkennung, Transaktionskennung, Kaufzeitpunkt und Gültigkeitsstatus verarbeitet werden. Diese Website bietet keinen Checkout und fragt keine Zahlungsdaten ab.</p><p>Für die Abwicklung und Bereitstellung gekaufter Leistungen kommt Art. 6 Abs. 1 lit. b DSGVO in Betracht, für gesetzliche Pflichten gegebenenfalls Art. 6 Abs. 1 lit. c DSGVO. <span class="pending-detail">Die konkreten Empfänger, Vertragsrollen, Aufbewahrungsfristen und Löschregeln sind vor der Kauf-Freischaltung zu bestätigen.</span></p>
    <h2>9. Kinder und Eltern</h2><p>Novaire ist für Schülerinnen und Schüler der Klassen 5–13 mit einem geplanten Mindestalter von 10 Jahren vorgesehen. Das bedeutet nicht, dass Zehnjährige eigenständig jeden Vertrag schließen oder in jede Datenverarbeitung einwilligen können.</p><p>Bei einwilligungsbasierter Verarbeitung im Rahmen eines direkt an Kinder gerichteten Online-Dienstes ist in Deutschland für unter 16-Jährige grundsätzlich die Einwilligung beziehungsweise Zustimmung der Sorgeberechtigten nach Art. 8 DSGVO erforderlich. Dafür sind angemessene Anstrengungen zur Überprüfung erforderlich. Für Minderjährigenverträge gelten daneben die Regeln des BGB.</p><p class="pending-detail">Im aktuellen Onboarding gibt es zwei vom Nutzer bedienbare Bestätigungen zu Elternzustimmung sowie Datenschutz/Bedingungen. Das ist hier ausdrücklich nicht als verifizierte Elternzustimmung dargestellt. Ein geeigneter, dokumentierter und altersgerechter Elternprozess muss vor Öffnung der entsprechenden Funktionen für Kinder geprüft und umgesetzt werden.</p>
    <h2>10. Empfänger und Übermittlung ins Ausland</h2><p>Je nach Funktion sind Hosting-, E-Mail-, Backend-, KI- und Abrechnungsdienstleister beteiligt. Ein Empfänger außerhalb des EWR oder Zugriff von dort kann zusätzliche Garantien nach Art. 44 ff. DSGVO erfordern. Ein Angemessenheitsbeschluss oder Standardvertragsklauseln dürfen nur genannt werden, wenn sie für den konkreten Anbieter und die konkrete Verarbeitung tatsächlich greifen.</p><p class="pending-detail">Anbieterregister mit juristischen Vertragspartnern, Rollen, Regionen, Unterauftragnehmern und einschlägigen Übermittlungsgrundlagen ergänzen. Auch prüfen, ob eine Datenschutz-Folgenabschätzung erforderlich ist.</p>
    <h2>11. Aufbewahrung und Löschung</h2><p>Daten dürfen nicht länger als für den jeweiligen Zweck erforderlich gespeichert werden, soweit keine rechtlichen Pflichten entgegenstehen. Kontodaten, Lerninhalte, Audio, Supportnachrichten, Sicherheitsprotokolle und Kaufnachweise benötigen unterschiedliche Regeln. Technische Backups können gesonderte Löschzyklen haben.</p><p class="pending-detail">Ein tatsächliches Löschkonzept einschließlich Konto-Löschung, Aufbewahrung beim KI-Anbieter und Backup-Fristen muss bestätigt werden. Dieser Entwurf erfindet keine Fristen und verspricht keine technisch ungeprüfte Sofortlöschung.</p>
    <h2>12. Deine Rechte</h2><p>Unter den gesetzlichen Voraussetzungen hast du Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung und Datenübertragbarkeit. Eine erteilte Einwilligung kannst du für die Zukunft widerrufen; die Rechtmäßigkeit der vorherigen Verarbeitung bleibt davon unberührt. Bei Verarbeitungen nach Art. 6 Abs. 1 lit. f DSGVO besteht ein Widerspruchsrecht nach Art. 21 DSGVO aus Gründen deiner besonderen Situation; gegen Direktwerbung besteht ein jederzeitiges Widerspruchsrecht.</p><p>Schreibe dazu an <a href="mailto:support@novaireai.de">support@novaireai.de</a>. Zur Vermeidung unberechtigter Datenweitergabe kann eine angemessene Identitätsprüfung nötig sein. Sende nicht unaufgefordert Ausweiskopien. Du kannst dich außerdem bei einer Datenschutzaufsichtsbehörde beschweren, insbesondere am Ort deines gewöhnlichen Aufenthalts, Arbeitsplatzes oder des vermuteten Verstoßes. Für Nordrhein-Westfalen: <a href="https://www.ldi.nrw.de/">Landesbeauftragte für Datenschutz und Informationsfreiheit NRW</a>.</p>
    <h2>13. Weitere Pflichtinformationen und Änderungen</h2><p class="pending-detail">Vor Freigabe je Verarbeitung ergänzen: ob die Datenbereitstellung erforderlich oder freiwillig ist und welche Folgen eine Nichtbereitstellung hat; gegebenenfalls Datenschutzbeauftragter, weitergehende Informationen zu automatisierten Entscheidungen und konkrete gesetzliche Aufbewahrungspflichten. Die endgültige Datenschutzerklärung muss den tatsächlichen Betrieb wiedergeben.</p>`
  },
  agb: {
    title: 'Nutzungsbedingungen / AGB',
    body: `<p class="draft-notice"><strong>Entwurf zur Prüfung, noch keine freigegebenen Vertragsbedingungen.</strong><br>Novaire ist noch nicht im App Store veröffentlicht. Dieser Text bildet das vorgesehene Angebot ab. Preise, Leistungsgrenzen, Vertragsschluss und Verbraucherinformationen sind vor dem Verkaufsstart zu vervollständigen.</p>
    <h2>1. Anbieter und Geltungsbereich</h2><p>Vorgesehener Anbieter ist Armin Brnicanin, Hopfenstraße 60, 51109 Köln, Deutschland, erreichbar unter <a href="mailto:support@novaireai.de">support@novaireai.de</a>. Die endgültige Betreiberstellung wird vor Veröffentlichung bestätigt. Novaire richtet sich zunächst an Nutzer in Deutschland.</p><p>Diese Website dient der Information. Über sie wird kein Abonnement abgeschlossen. Für die spätere Nutzung der App gelten die bei Vertragsschluss wirksam einbezogenen Bedingungen und die einschlägigen gesetzlichen Rechte.</p>
    <h2>2. Wobei Novaire unterstützt</h2><p>Novaire ist eine KI-gestützte Lernhilfe mit Erklärungen, Lernpfaden, Karteikarten und weiteren Lernwerkzeugen. Sie ersetzt weder Unterricht noch die eigene Prüfung wichtiger Informationen. KI-Ausgaben können sachlich falsch, unvollständig oder unpassend sein. Es wird keine bestimmte Note, Prüfungserfolg oder dauerhafte Verfügbarkeit eines einzelnen KI-Modells versprochen. Gesetzliche Ansprüche wegen mangelhafter Leistungen bleiben unberührt.</p>
    <h2>3. Alter und Zustimmung</h2><p>Geplant ist die Nutzung ab 10 Jahren für die Klassen 5–13. Minderjährige benötigen die rechtlich erforderliche Mitwirkung ihrer Sorgeberechtigten, insbesondere bei kostenpflichtigen Verträgen. Datenschutzrechtliche Einwilligungen sind davon getrennt zu behandeln. Zwei selbst gesetzte Häkchen werden in diesem Entwurf nicht als verlässlicher Nachweis einer Elternzustimmung bezeichnet.</p><p class="pending-detail">Vor App-Start: zulässigen Vertragsschluss für Minderjährige, Altersprüfung und Elternprozess konkret festlegen und technisch verifizieren.</p>
    <h2>4. Dein Konto</h2><p>Für personalisierte Funktionen kann ein Konto erforderlich sein. Zugangsdaten sollen geheim gehalten und Angaben korrekt gemacht werden. Teile keine Konten oder Inhalte Dritter ohne Berechtigung. Melde einen vermuteten unberechtigten Zugriff an den Support. Welche Funktionen ohne Konto verfügbar sind, ergibt sich aus der finalen App-Version.</p>
    <h2>5. Free, Nova und Einzelkäufe</h2><ul><li><strong>Free:</strong> Einstieg mit dem in der App beschriebenen kostenlosen Funktionsumfang.</li><li><strong>Nova:</strong> kostenpflichtiges Abonnement für den jeweils vor Kauf ausgewiesenen Leistungsumfang. Die angebotenen Laufzeiten müssen zum Start bestätigt werden.</li><li><strong>24-Stunden-Pass:</strong> vorgesehener einmaliger Kauf für zeitlich begrenzten Zugang. Leistungsumfang und genauer Beginn der 24 Stunden müssen vor Kauf ausdrücklich angegeben werden.</li><li><strong>Präsentationen:</strong> vorgesehener einmaliger Kauf. Anzahl, Bearbeitungsdauer, Exportmöglichkeiten und späterer Zugriff müssen vor Kauf eindeutig beschrieben werden.</li></ul><p>Es gibt hier keine erfundenen Preise, Ersparnisse, unbegrenzten Kontingente oder zugesagten Modell-Upgrades. Maßgeblich müssen die klaren Produktinformationen im späteren Kaufdialog sein. Bereits zugesagte Leistungen dürfen nicht beliebig nachträglich geändert werden.</p>
    <h2>6. Warum es kostenpflichtige Angebote gibt</h2><p>Die Verarbeitung von KI-Anfragen verursacht bei den eingesetzten Anbietern laufende Kosten. Diese werden nicht automatisch als Einzelgebühr für jede Nachricht an dich weitergegeben. Eine Zahlung setzt eine ausdrücklich bestätigte Bestellung des angebotenen Produkts voraus. Kostenlose Nutzung wird nicht allein durch das Absenden einer Frage zum kostenpflichtigen Abonnement.</p>
    <h2>7. App-Store-Kauf, Verlängerung und Kündigung</h2><p>Käufe sind über den Apple App Store vorgesehen; RevenueCat unterstützt die technische Zuordnung der Berechtigungen zum App-Konto. Preis, Zahlungsintervall und gegebenenfalls automatische Verlängerung werden vor dem Kauf im Store-Dialog angezeigt. Einmalige Käufe sind keine automatisch verlängernden Abonnements.</p><p>App-Store-Abonnements lassen sich über die Apple-Abonnementverwaltung verwalten. Das Löschen der App oder eine Konto-Löschanfrage beendet nicht automatisch ein separat über Apple verwaltetes Abonnement. Kaufwiederherstellung und Kontozuordnung sind vor dem Start anhand der tatsächlich angebotenen Produkte zu testen.</p><p class="pending-detail">Angebotene Laufzeiten, Vertragspartnerrollen, Kündigungsbedingungen und konkrete App-Store-Vertragsinformationen müssen final ergänzt werden. Für App-Käufe dürfen keine zusätzlichen Website-Regelungen erfunden werden, die dem tatsächlichen Kaufprozess widersprechen.</p>
    <h2>8. Widerruf und gesetzliche Verbraucherrechte</h2><p>Gesetzliche Verbraucherrechte bleiben bestehen. Ein Widerrufsrecht entfällt nicht pauschal durch die App-Nutzung oder durch Zustimmung zu AGB.</p><p class="pending-detail">Vor dem Verkaufsstart sind passende Widerrufsbelehrung, Musterformular und der konkrete Ablauf für digitale Inhalte beziehungsweise digitale Dienstleistungen zu prüfen. Ein gegebenenfalls vorzeitiger Leistungsbeginn und ein mögliches Erlöschen des Widerrufsrechts benötigen die jeweils gesetzlichen Voraussetzungen und einen dazu passenden Store-Prozess. Dieser Entwurf ersetzt diese Informationen nicht.</p>
    <h2>9. Eigene Inhalte und faires Verhalten</h2><p>Lade nur Material hoch, das du verwenden darfst. Nutze Novaire nicht für Belästigung, rechtswidrige Inhalte, die Weitergabe fremder personenbezogener Daten oder die Umgehung von Zugangsbeschränkungen. Beachte die Regeln deiner Schule, insbesondere bei Prüfungen und bewerteten Arbeiten. Novaire ist als Lernhilfe gedacht.</p><p>Die Verarbeitung deiner Eingaben ist nur im Umfang vorzusehen, der zur gewählten Funktion erforderlich und rechtlich zulässig ist. Eine pauschale Übertragung sämtlicher Rechte an eigenen Inhalten oder eine pauschale Freigabe zum Modelltraining wird hier nicht verlangt.</p>
    <h2>10. Störungen, Änderungen und Verantwortung</h2><p>Bei technischen Problemen kannst du dich an den Support wenden. Eine absolute Fehlerfreiheit oder unterbrechungsfreie Verfügbarkeit wird nicht versprochen. Dieser Hinweis schließt keine gesetzliche Haftung aus und beschränkt weder zwingende Gewährleistungsrechte noch zwingende Schutzvorschriften für Verbraucher.</p><p class="pending-detail">Etwaige Regelungen zu Leistungsänderungen, Sperrungen, Haftung und Beendigung müssen verhältnismäßig, gesetzeskonform und zum tatsächlichen Betrieb passend geprüft werden. Es wird kein pauschaler Haftungsausschluss verwendet.</p>
    <h2>11. Datenschutz und Kontakt</h2><p>Hinweise zur Datenverarbeitung findest du im <a href="datenschutz.html">Datenschutzentwurf</a>. Fragen zu Zugang, Käufen und Lernfunktionen: <a href="mailto:support@novaireai.de">support@novaireai.de</a>.</p>`
  },
  support: {
    title: 'Wir helfen dir weiter.',
    body: `<p>Ob eine Frage zu Novaire, ein technisches Problem oder Feedback: Schreib uns an <a href="mailto:support@novaireai.de">support@novaireai.de</a>.</p><p>Ansprechpartner: Armin Brnicanin, Gründer von Novaire.</p>
    <h2>Damit wir dir helfen können</h2><p>Beschreibe kurz, was du machen wolltest und was stattdessen passiert ist. Bei einem technischen Problem helfen das Gerätemodell, die iOS-Version und die App-Version. Einen Screenshot kannst du anhängen — bitte verdecke darin persönliche Daten anderer Personen.</p><p>Schicke keine Passwörter, API-Schlüssel, vollständigen Zahlungsdaten oder Ausweiskopien. Für die erste Anfrage reicht eine kurze Beschreibung. Wir versprechen hier keine feste Antwortzeit, die noch nicht organisatorisch abgesichert ist.</p>
    <h2>Häufige Fragen</h2>
    <details><summary>Wo kann ich Novaire herunterladen?</summary><p>Novaire ist noch nicht im App Store veröffentlicht. Sobald die App verfügbar ist, ergänzen wir auf der Startseite den offiziellen Download-Link. Hier gibt es aktuell keine Registrierung oder Warteliste.</p></details>
    <details><summary>Für wen ist Novaire gedacht?</summary><p>Für Schülerinnen und Schüler der Klassen 5–13 in Deutschland. Geplant ist ein Mindestalter von 10 Jahren. Für Kinder und Jugendliche müssen die erforderlichen Eltern- und Vertragsprozesse vor dem Start abschließend geklärt sein.</p></details>
    <details><summary>Kann ich kostenlos starten?</summary><p>Ein Einstieg mit Free ist vorgesehen. Nova, ein 24-Stunden-Pass und Präsentationen sind zusätzliche geplante Angebote. Die finalen Preise und enthaltenen Leistungen werden vor einem Kauf in der App angezeigt.</p></details>
    <details><summary>Kann Nova auch Fehler machen?</summary><p>Ja. Nova verwendet KI und kann sich irren. Frage nach einer Erklärung, vergleiche wichtige Aussagen mit Unterrichtsmaterial und wende dich bei Unsicherheit an eine Lehrkraft.</p></details>
    <details><summary>Wie verwalte ich später mein Abo?</summary><p>App-Store-Abonnements verwaltest du auf deinem iPhone unter Einstellungen → dein Name → Abonnements. Die App zu löschen reicht nicht zur Kündigung. Ob und welche Abos verfügbar sind, ergibt sich erst aus dem finalen Angebot.</p></details>
    <details><summary>Ich möchte Auskunft oder meine Daten löschen lassen.</summary><p>Schreibe an <a href="mailto:support@novaireai.de">support@novaireai.de</a>, möglichst von der zu deinem Konto gehörenden E-Mail-Adresse. Nenne dein Anliegen, aber sende keine Passwörter. Weitere Informationen stehen im <a href="datenschutz.html">Datenschutzentwurf</a>.</p></details>
    <h2>Für Eltern</h2><p>Sie möchten wissen, wie Novaire funktioniert oder welche Daten verarbeitet werden? Schreiben Sie uns. Teilen Sie dabei zunächst nur die Angaben mit, die für Ihre Frage nötig sind. Novaire verspricht weder bestimmte Noten noch eine fehlerfreie Bewertung der Fähigkeiten eines Kindes.</p>`
  }
};
